// Templates for the temp Cargo project used by the compilation driver.

use std::path::Path;

/// Generate the Cargo.toml for a temp compilation project.
pub fn cargo_toml(runtime_path: &Path) -> String {
    let runtime_abs = std::fs::canonicalize(runtime_path)
        .unwrap_or_else(|_| runtime_path.to_path_buf());

    format!(
        r#"[package]
name = "ish-compiled"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ish-runtime = {{ path = "{}" }}
"#,
        runtime_abs.display()
    )
}

/// Wrap generated Rust source with necessary boilerplate for a cdylib.
pub fn lib_rs(generated_source: &str) -> String {
    format!(
        r#"// Auto-generated by ish-codegen
#![allow(unused_variables, unused_mut, dead_code, unused_parens)]

{}
"#,
        generated_source
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_cargo_toml_generation() {
        let toml = cargo_toml(Path::new("/some/path/ish-runtime"));
        assert!(toml.contains("[package]"));
        assert!(toml.contains("crate-type = [\"cdylib\"]"));
        assert!(toml.contains("ish-runtime"));
    }

    #[test]
    fn test_lib_rs_generation() {
        let source = lib_rs("fn foo() -> i64 { 42 }");
        assert!(source.contains("fn foo() -> i64 { 42 }"));
        assert!(source.contains("Auto-generated"));
    }
}
